# Generated by Django 3.2.9 on 2021-12-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_alter_rater_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rater',
            options={},
        ),
    ]
