# Generated by Django 3.2.9 on 2021-12-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0005_alter_rater_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rater',
            options={},
        ),
    ]
