# Generated by Django 3.2.9 on 2021-11-28 01:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rater', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_file', models.FileField(upload_to='adverMedia/%Y/%m/%d/')),
                ('reward', models.PositiveIntegerField()),
                ('num_views', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_website', models.URLField()),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=6000)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='owner.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answered', to='rater.rater')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.business'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='viewers',
            field=models.ManyToManyField(to='rater.rater'),
        ),
    ]
