# Generated by Django 3.2.9 on 2021-12-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_advertisement_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='owner.advertisement'),
        ),
    ]
