# Generated by Django 3.2.9 on 2021-12-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_answer_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
    ]
