# Generated by Django 3.2.9 on 2021-12-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_business_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
    ]
