# Generated by Django 3.2.9 on 2021-12-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_business_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'permissions': (('access_owner', 'Owner Stuff'),), 'verbose_name_plural': 'Businesses'},
        ),
    ]
