# Generated by Django 3.2.9 on 2021-12-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0006_alter_rater_options'),
        ('owner', '0011_alter_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answered', to='rater.rater'),
        ),
    ]
